version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-service
    ports:
      - "6333:6333" # API HTTP e Dashboard
      - "6334:6334" # API GRPC (Alta performance interna)
    environment:
      - QDRANT__SERVICE__ENABLE_STATIC_CONTENT=1
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

volumes:
  qdrant_data:
